# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactiveMVVM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReactiveMVVM

pod 'ReactiveSwift', '~> 3.0'
pod 'ReactiveCocoa', '~> 7.0'

end
